---
- name: Build /Push / Install Custom EEs
  hosts: all
  gather_facts: false
  vars_files:
    - vars/ee.yml
  vars:
    # what is the path where the EE build files are stored
    path_ee: "{{ playbook_dir }}/build_files"

    # remote directory to store the EE Build files
    remote_path: /tmp

    # private automation hub host
    pah_host: lab-aaphub.tiger.lab

    # credential name used in AAP
    pah_cred: Automation Hub Container Registry

  tasks:
    - include_tasks: tasks/create_ee.yml
      loop: "{{ execution_envs }}"
      loop_control:
        loop_var: ee
        label: "{{ ee }}"

