---
- name: Check previous job for change entries
  hosts: localhost
  vars: 
    tower_server: 10.1.10.44
  tasks:

    # We have the ID of the currently running workflow job via the variable 'tower_workflow_job_id'
    # So we will use that to get the Template jobs that are associated with it
    - name: Get the Job ID for the first playbook run
      uri:
        url: https://{{ tower_server }}/api/v2/workflow_jobs/{{ tower_workflow_job_id }}/workflow_nodes/
        method: GET
        user: "{{ tower_username }}"
        password: "{{ tower_password }}"
        body_format: json
        validate_certs: False
        force_basic_auth: yes
        status_code:
          - 200
      register: response

    # Now that we have the Job ID of the first job of the workflow, we need to grab the job events of that job
    - name: Get the Job Results for the first playbook run
      uri:
        url: https://{{ tower_server }}/api/v2/jobs/{{ job }}/job_events/
        method: GET
        user: "{{ tower_username }}"
        password: "{{ tower_password }}"
        body_format: json
        validate_certs: False
        force_basic_auth: yes
        status_code:
          - 200
      register: jdata

    # Now that we have the Job Events, we will do a quick peek through them to see if we made any changes
    # There is no reason to try and build a report if no changes where made
    - set_fact:
        job_changed: "{%- set changed = namespace(v=false) -%}\
                      {%- for c in jdata.json.results -%}\
                        {%- if c.event == 'runner_on_ok' and c.changed -%}\
                          {%- set changed.v = true -%}\
                        {%- endif -%}\
                      {%- endfor -%}\
                      {{- changed.v -}}"

    # Display a quick message if we didn't detect any changes.  That way they aren't wondering if the job
    # didn't complete, etc.. 
    - debug: 
        msg: No Changes were detected
      when: not job_changed

    # From here, we only continue if a change was actually made on the previous playbook
    - when: job_changed
      block:

      - name: Create report of changes
        template:
          src: templates/changes.csv.j2
          dest: changes.csv 

      - name: Display the Results
        debug:
          msg: "{{ lookup('file', 'changes.csv') }}"

      # From here you can add more data to the template and email it out etc...