---
- name: Check previous job for change entries
  hosts: localhost
  tasks:

    - name: Get the Job ID for the first playbook run
      uri:
        url: https://10.1.10.44/api/v2/workflow_jobs/{{ tower_workflow_job_id }}/workflow_nodes/

        method: GET
        user: "{{ tower_username }}"
        password: "{{ tower_password }}"
        body_format: json
        validate_certs: False
        force_basic_auth: yes
        status_code:
          - 200
          - 204
          - 400
      register: response
      changed_when: response.status == 200

    - name: display job var
      debug:
        var: response.json.results[0].summary_fields.job.id