- name: Test of vars prompt / Tower Survey
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Call our job
      awx.awx.job_launch:
        name: Set Stat
        wait: yes
      register: job
      
