
# We will now grab each page of the Job Events
- name: Get the events on page {{ page }}
  ansible.builtin.uri:
    url: https://{{ tower_server }}/api/v2/jobs/{{ job_id }}/job_events/?event=runner_on_ok&changed=true&page_size={{ page_size }}&page={{ page }}
    method: GET
    user: "{{ tower_username }}"
    password: "{{ tower_password }}"
    body_format: json
    validate_certs: False
    force_basic_auth: yes
    status_code:
      - 200
  register: events

# You can also add in a URL link back to the actual job run by using
# Workflow: https://{{ tower_server }}/#/jobs/workflow/{{ tower_workflow_job_id }}/output
# Job:      https://{{ tower_server }}/#/jobs/playbook/{{ job_id }}/output
# so they can more easily view the results
- name: Create report of changes on page {{ page }}
  ansible.builtin.template:
    src: templates/changes.html.j2
    dest: "{{ playbook_dir }}/reports/fragments/page-{{ page }}.html"
