---
version: 2.0


#build_arg_defaults:
  #EE_BASE_IMAGE: jc-aap23-hub/ee-supported-rhel8:latest
  #EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-21/ee-supported-rhel8'
  #EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-20-early-access/ee-supported-rhel8:2.0.0'

# ansible_config: 'ansible.cfg'

dependencies:
  galaxy: galaxy.yml
  python: python.txt

images:
  base_image:
    name: jc-aap23-hub.tiger.lab/ee-supported-rhel8:latest
  builder_image:
    name: jc-aap23-hub.tiger.lab/ansible-builder-rhel8:latest
#    signature_original_name: registry.redhat.io/ansible-automation-platform-21/ansible-builder-rhel8:latest
