---
collections:
  - name: community.vmware
    version: 3.2.0
  - name: community.routeros
    version: 2.6.0
  - name: community.general
    version: 6.2.0
  - name: ansible.netcommon
    version: 4.1.0
  - name: ansible.utils
    version: 2.8.0
  - name: community.windows
    version: 1.12.0
