---
collections:
  - name: community.vmware
  - name: community.routeros
    version: 2.0.0
  - name: community.general
    version: 4.4.0
  - name: ansible.netcommon
    version: 2.4.0
  - name: ansible.utils
    version: 2.4.2
