---
version: 1.0

build_arg_defaults:
  EE_BASE_IMAGE: jc-aap23-hub.tiger.lab/ee-supported-rhel8:latest
  #EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-21/ee-supported-rhel8'
  #EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-20-early-access/ee-supported-rhel8:2.0.0'

# ansible_config: 'ansible.cfg'

dependencies:
  galaxy: galaxy.yml
  python: python.txt
